spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/finanCerto

    username: ${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD}}
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: ${SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT:-1}
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

fastapi:
  base-url: ${FASTAPI_BASE_URL:http://financerto-fastapi:8001/api}

server:
  port: ${SERVER_PORT:8080}
